CREATE TABLE IF NOT EXISTS aPowerStats (
    id INTEGER PRIMARY KEY NOT NULL,
    ts TEXT NOT NULL, /* %Y%m%dT%H%M%S */
    c1_use INTEGER,
    c1_cumul INTEGER,
    c1_peak INTEGER,
    c2_use INTEGER,
    c2_cumul INTEGER,
    c2_peak INTEGER,
    c3_use INTEGER,
    c3_cumul INTEGER,
    c3_peak INTEGER,
    c4_use INTEGER,
    c4_cumul INTEGER,
    c4_peak INTEGER,
    c5_use INTEGER,
    c5_cumul INTEGER,
    c5_peak INTEGER,
    c6_use INTEGER,
    c6_cumul INTEGER,
    c6_peak INTEGER,
    c7_use INTEGER,
    c7_cumul INTEGER,
    c7_peak INTEGER,
    c8_use INTEGER,
    c8_cumul INTEGER,
    c8_peak INTEGER,
    all_use INTEGER,
    all_cumul INTEGER,
    all_peak INTEGER,
    measures_count INTEGER,
    delta_ts TEXT, /* timestamp of previous measurement used for delta */
    update_ts TIMESTAMP DATETIME DEFAULT(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW'))  /* row inserted at timestamp  */
);
